### ISSUE TITLE
Issue with font widths

### ISSUE THREAD

**Issue by frisbee00** [mozilla/Fira#111]
Hi,
I'm running Arch Linux + XFCE and like Fira Sans as system font; except for a minor issue:
![test](https://cloud.githubusercontent.com/assets/6317854/9872895/e025701a-5bb9-11e5-81b9-6299a014ee29.gif)
The left end of the seek bar for the player shifts as the time changes. I don't see this with Droid Sans or DejaVu Sans or Liberation Sans. There is a similar issue in VLC (where timer shifts).
I'm not familiar with font design and if this is is related to a design choice, feel free to ignore and close the issue.

**Comment by jfkthame** [comment]
This is because the digits in Fira Sans are not monospaced; in particular, the "1" is narrower, though there are other variations too. And the media player UI apparently used a flexible/automatic layout where the seek bar occupies whatever space remains between the two auto-sized text fields with the timings.

You'd see a similar thing with various other fonts such as Helvetica or Arial.

Fira Sans does actually have monospaced digits available, by applying the Tabular Figures[1] feature. But the applications concerned may not offer a mechanism to specify that, in which case you're stuck with the default (proportional) digits.

So this is simply a result of a design choice in the font -- to have proportionally-spaced digits by default, for better spacing within running text -- combined with the kind of layout the media player uses, which assumed fixed-width digits.

In an ideal world, I suppose you'd be able to specify "Fira Sans with the 'tnum' feature" as your system font, and have it use the fixed-width digits; but I doubt that's supported at a system level.

[1] https://www.microsoft.com/typography/otspec/features_pt.htm#tnum
