### ISSUE TITLE
Publish versioned on npmjs.org?

### ISSUE THREAD

**Issue by anselmh** [mozilla/Fira#138]
Hi,

are there any plans to publish the package on npmjs.org so that one can fetch it properly via the registry as a dependency?

Thanks,
Anselm

**Comment by Schweinepriester** [comment]
+1

**Comment by idleberg** [comment]
+1

**Comment by pivanov** [comment]
Hey guys, 
do you still need npmjs version? We already have bower version http://bower.io/search/?q=fira

**Comment by anselmh** [comment]
I don’t use bower so npm would still be great to have.

**Comment by pivanov** [comment]
OK :) I'm on it :) I will update you soon guys :)

**Comment by Schweinepriester** [comment]
Thanks! :)

**Comment by idleberg** [comment]
Just for the record. I'm not fully satisfied with the implementation of both, Bower and npm. I'm well aware of several methods to install the Fira family using Node:

1. npm already supports `user/repo` ([documentation](https://docs.npmjs.com/files/package.json#dependencies))
2. With Git is present, repositories can be installed using a `preinstall` script
3. Popular task runners like gulp can clone repositories

Still, I would appreciate proper support for Fira as a Node package. Since `npm publish` will handle the creation of tags on here GitHub, it's pretty hassle-free and even quicker than using the equivalent Git commands.

```bash
# using git
git tag -a 1.0.0 -m "1.0.0"
git push --tags
# using npm:
npm publish major|minor|patch
```

While I appreciate @pivanov's effort to maintain a shim repository, I wonder for how long it will be supported in the future. With Git and npm coupled, there should be little to no risk of future abandonment. Also, the shim repository seems to have a different versioning scheme.

**Comment by patrykdesign** [comment]
@idleberg if what you suggests satisfies the needs, then please proceed with this repo getting published on npm. @pivanov is on my team, so he can help out with the implementation if needed. Also if you can let us know what would the best way to sync the two repos whenever I publish an update to Fira, that would be appreciated!

**Comment by pivanov** [comment]
@idleberg I agree with you but still I think is a good idea to have these fonts as npm or bower modules for people who want to use them. The npm package is ready for use: https://www.npmjs.com/package/mozilla-fira-pack
We can work to implement features like: using all fonts or just couple of them and other cool things like these. I have some ideas how we can sync the repos/modules/packs so soon we will have something to share with you guys :)

**Comment by pivanov** [comment]
I will close this one. If you have any issues please open an issue here or ping me. Thanks :)
