### ISSUE TITLE
Is it going to be mantained?

### ISSUE THREAD

**Issue by captainepoch** [mozilla/Fira#210]
Hello all.

I was asking myself if this font is going to be mantained by someone.

**Comment by atheistray** [comment]
Since Mozilla abandoned the development of Firefox os, they stopped the development of this typeface. The good news is that the developer of this typeface carrois apostrophe studio is still expanding this typeface. This project has been moved to their GitHub page:
https://github.com/carrois/Fira
I suggest everyone who loves this gorgeous typeface move to New page too!

**Comment by indolering** [comment]
I just submitted [a PR](https://github.com/mozilla/Fira/pull/212) updating the README.
