### ISSUE TITLE
Fractional coordinates in Hair

### ISSUE THREAD

**Issue by IvanUkhov** [mozilla/Fira#51]
Hello,

I am looking at [Fira Sans Hair](https://github.com/mozilla/Fira/blob/master/otf/FiraSans-Hair.otf) right now and have the following concern. It is the thinnest weight in the family, but it does not look like a master. It feels like it was produced by extrapolation from some thicker weight, and that extrapolation did not do a good job.

Most of the nodes have fractional coordinates. I understand that, at this weight, it is challenging to work with integers, but there are some really questionable cases. In particular, there is no capital letter aligned to the cap height. Have a look at the top nodes of such letters as E, H, I, and T: they are shorter than 681 but taller than 680.

May I ask if it was intentional and, if so, how it affects text rendering.

Thank you.

Regards,
Ivan

**Comment by patrykdesign** [comment]
Below is an explanation on why HAIR is the way it is...
Fira Sans Hair is not the thinnest weight. 
The thinnest Master is at 2 em. Fira Sans Hair (14 em) is interpolated between this Master and the Light Master (30 em). So yes, this is an integer – but the result of a controlled interpolation, not an extrapolation.

All top nodes of the mentioned glyphs are constantly at 680,85. It could be that the renderer doesn’t catch the points because caps height is at 681.
The decision was to start rounding interpolation values at 22 em; that corresponds to the weight „Thin“.
As for that, all weights below Thin are using fractional values.
Reason is that bevels and crucial points (i.e. connections) look better if they are interpolated exactly and rounding doesn’t affect the proportions as much if the weight get a bit bolder.

You could use Fira Thin (22 em) if you think the rendering results of Fira Hair (14 em) don’t work for the font sizes you intended.
In general, these hairline weights are technically still experimental because renderer can’t handle integer values yet. That’s why they were marked red in the version report.
Please see them as a gimmick if you want to play around with huge letters. They are not intended as perfectly rendered text fonts in text sizes.

**Comment by patrykdesign** [comment]
So this likely won't be fixed.
