### ISSUE TITLE
Lower line height in FiraMono?

### ISSUE THREAD

**Issue by PaBLoX-CL** [mozilla/Fira#67]
I know it's a not big deal, but I would really like a smaller line height, maybe there's a workaround  to do it locally?

Here's a comparison using Fira vs Meslo, both at 9px.

![license txt -code-fonts-powerline-fonts-firamono - vim_015](https://cloud.githubusercontent.com/assets/275754/5561909/193f6a18-8dd9-11e4-8833-095dd7533783.png)
![license txt -code-fonts-powerline-fonts-firamono - vim_014](https://cloud.githubusercontent.com/assets/275754/5561910/1a0a8fd6-8dd9-11e4-865b-5d888a870c39.png)

As you can see, Meslo have around 6 lines more.

**Comment by antanst** [comment]
Yes please. The inconveniently high line height is what currently prevents me from using this otherwise excellent font in Emacs and in various terminals.

**Comment by kennethormandy** [comment]
Personally I haven’t had this problem, but Fira Mono’s line height needs to work alongside the Sans, so I’m pretty sure it’s not practical or possible to change.

An alternative would be to run it through a [customizer like Input has](http://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputSans&width=300&weight=300&line-height=1.2&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&customize=please), where you can change the line height before downloading. I think this would actually be possible for someone else to develop thanks to Fira’s licensing.

**Comment by patrykdesign** [comment]
@carrois can you comment on this?

**Comment by carrois** [comment]
If we reduce line height now we will get problems with the Latin extensions, the Greek and Cyrillic extensions later. We know that 1.4 is more than other monospaced typefaces have but we need that space for all the coming diacritical marks in Vietmames, African languages and many more.
The only way to solve or circumvent that is to provide a FiraMono-Code or FiraCode ...!? We already disscued a similar idea some month ago. Patryk, what do you think? Is a “FiraCode” good idea?

**Comment by jfkthame** [comment]
I don't think the default line-height resulting from the ascent/descent/linegap metrics specified in the font should be designed to suit the exceptional cases with stacked diacritics. Rather, it should be designed (in both Fira Sans and Fira Mono) for optimal appearance for the majority use-case. It's still possible for authors/designers to increase the line height when working with diacritic-heavy languages, but the extra line-spacing needed for those cases should not be imposed by default across all uses. It's OK if certain particularly tall glyphs such as Ễ or Ṹ extend beyond the font's nominal ascent.

(Also, note that in many software systems, it's more difficult to adjust the line spacing to be tighter than the default provided by the font, while looser spacing is generally easy to achieve.)

**Comment by carrois** [comment]
Yes, thats right.
On the other hand we agreed to set the linespacing to 1400 (1.4) month ago.
To change it now is possible, even no problem, but is it what “we” want?
In my opinion FiraMono looks much better than Malso does. And that is a result of the linespacing, too.

I dont see any reason to change the linespacing. Do you?
If so, please let me know and please let me know the value.

best,
_r



Am 13.03.2015 um 16:30 schrieb jfkthame <notifications@github.com>:

**Comment by jfkthame** [comment]
Well, in FirefoxOS up till now, we've been using Fira 3 with its default linespacing set to 1.2, so moving to 1.4 is likely to affect the layout of quite a lot of screens/apps (except in cases where the designers have explicitly specified a fixed line-height, rather than a multiple of the font's default). It will also mean that text on many web pages (again, wherever the font's line height is used as a basis) will be more spread out, which results in less information being visible on the limited-size screen at any one time.

As such, my preference would be to stay with the 1.2 line height that we've been working with until now (we have this specified via ascent:935; descent:-265; line-gap:0 in the font tables). But I think the FirefoxOS designers should have the final say on this; if they're happy with 1.4, understanding that this will result in layout changes in some cases, that's fine.

What I definitely want to avoid is the need for us to patch the fonts locally to reduce the line-height before we use them in FirefoxOS. We've done that in the past but I don't want to have to revisit this every time we update.

@patrykdesign, I think you and your team need to make the final call here: are we going to move to the 1.4 linespacing that's currently in Fira 4, understanding that this will have some impact on existing layout, or do we want to keep using 1.2 as in (our version of) Fira 3?

**Comment by patrykdesign** [comment]
@jfkthame I did some tests, ran the latest Firefox OS builds running v.2.0 and v.2.2 (with Fira 3.1), the line heights looked identical and appear to be 1.4.
The fonts in the paragraph are 25px with what appears to the 34.5px leading = line height 1.38x.
In the browser I am seeing similar line height spacing. ie wikipedia.

I think the line height at 1.4 seems really nice. Personally I'd like to keep it.
Fira with line height of 1.4 (as seen on current devices):
![25-34 5](https://cloud.githubusercontent.com/assets/1503049/6647324/854ff492-c9a3-11e4-8c6c-4913982a5357.png)



Fira with line height of 1.2 (Its a mock up, I can't seem to find a way to see it in current builds, Firefox OS 1.4+)
![25-30](https://cloud.githubusercontent.com/assets/1503049/6647326/8f52fc82-c9a3-11e4-977b-9d79d3649156.png)




As far as Fira Mono, if we do a code version we can add special ligatures so it. So I am okay with a Fira Code, not sure how much overhead that would to maintain all the fonts, but I am thinking that Fira Mono will likely a prime candidate for more community support as we try to finish off Fira Sans. So perhaps in the next update (Mono 3.2) we can spin off 2 versions... one to match Fira Sans line height and Fira Code with a tighter line height.

**Comment by patrykdesign** [comment]
I'd like to keep Fira Sans line height as is, as I see in v.2 and v.2.2 of the OS. I am just not convinced it is actually 1.2x, it appears 1.4x.

**Comment by carrois** [comment]
Have a look at the three screen shots.
All versions come with equal values.

![bildschirmfoto 2015-03-14 um 10 17 03](https://cloud.githubusercontent.com/assets/7803690/6651089/efff0450-ca33-11e4-9ae3-8539a4a1571c.png)
![bildschirmfoto 2015-03-14 um 10 18 32](https://cloud.githubusercontent.com/assets/7803690/6651088/effe939e-ca33-11e4-8fbc-8c7baa9c55cf.png)
![bildschirmfoto 2015-03-14 um 10 19 45](https://cloud.githubusercontent.com/assets/7803690/6651087/effe2594-ca33-11e4-9f79-82744b3d6bd2.png)

**Comment by PaBLoX-CL** [comment]
Wouldn't be possible to have a version with smaller line height, thinking when you use FiraMono to code? (FiraCode, seemed nice enough :P).

I understand the issues with diacritics, but when coding you aren't likely to use them at all.

**Comment by patrykdesign** [comment]
This looks to be fixed in Fira Sans v.4.1 & Mono 3.2.

**Comment by alphapapa** [comment]
I would really like to see a FiraCode with a 1.0 line height.  I usually use DejaVu Sans Mono in Emacs, but I do like some of the features of Fira Mono.  However, on my screen, even with Fira Mono 3.2, the line height is still too much, and I get 4 fewer lines of code in Emacs compared to DejaVu Sans Mono.  

This makes it useless for me.  I gain nothing, because I don't have any trouble reading text with DejaVu's line height  And I lose efficiency and waste time by seeing less code and having to scroll more.

It's a shame, because it's a nice font.  Please consider making one that's more useful and less spaced-out.  As someone mentioned, it's usually easy to increase line height (like in Emacs), but not so easy to decrease it (impossible in Emacs).

**Comment by patrykdesign** [comment]
@alphapapa we are working on a Fira Code, it should have a 1.0 line height. road map:
https://docs.google.com/document/d/1fLxzQsULTv43umIhpB9Gv3Gi7aOBONHbqEbwZIipmxw/edit
