### ISSUE TITLE
Add capital ß ("Eszett") => ẞ

### ISSUE THREAD

**Issue by Schweinepriester** [mozilla/Fira#80]
Please add capital ß ("Eszett") => ẞ

It's a little revolution for the german language that its finally official.

See <http://en.wikipedia.org/wiki/Capital_%E1%BA%9E>.

If capable of german, the german articles are probably the better choice for reference, see e.g.
- <http://de.wikipedia.org/wiki/Gro%C3%9Fes_%C3%9F>
- <https://dasauge.de/aktuell/design/e1133>

**Comment by fitojb** [comment]
I can see capital ß in Fira since many releases ago. Are you sure you have the latest version? Also, make sure you’re not using a webfont version, which obviously has its character set crippled.
![captura de pantalla de 2015-05-02 22 23 19](https://cloud.githubusercontent.com/assets/554953/7443546/0f2544c2-f11a-11e4-8d54-eb3926ce67ca.png)

**Comment by Schweinepriester** [comment]
ah, of course, thanks! :)

PS: i see what you did there \m/ B-)
