### ISSUE TITLE
Umlaut glitch in latest Fira Sans (4.1)

### ISSUE THREAD

**Issue by funtoosh** [mozilla/Fira#86]
Hi there,
I have a problem displaying Umlaute, namely the capital letters Ö, Ä und Ü with Fira, see here: http://www.flurstuecke.com/015/presse 
The word Öffentlichkeitsarbeit has misplaced dots before the Ö (latest Firefox on Mac). Tried finding an error with text encoding, but hat does not seem to be the case. 
Any ideas? Didn't notice that one before. 
Beautiful font, by the way!!!
Cheers,
-f

**Comment by funtoosh** [comment]
![bildschirmfoto 2015-05-30 um 10 24 40](https://cloud.githubusercontent.com/assets/506433/7896335/f207dfec-06b5-11e5-82ed-85130af11836.png)

**Comment by jfkthame** [comment]
Very strange -- it looks fine here, on both Mac and Windows.

**Comment by jfkthame** [comment]
![screenshot-2015-05-30](https://cloud.githubusercontent.com/assets/1706499/7896701/5727afb6-06ba-11e5-8d39-0d239a9e4e74.png)

**Comment by funtoosh** [comment]
Strange indeed! It does not work on my client's Macs, nor does it work on my iMac (10.6).
On my fairly old-ish office Mac (10.5) it's fine though …

**Comment by funtoosh** [comment]
The prob persists on Chrome & Safari (all Mac OS X 10.6.8), here's what Chrome renders:

![bildschirmfoto 2015-05-30 um 12 58 14](https://cloud.githubusercontent.com/assets/506433/7896979/b10f8f2e-06cb-11e5-99c4-a049424e11b1.png)

Neither zooming nor manipulating line-height nor using HTML-entities solves the problem.

**Comment by jfkthame** [comment]
I still can't reproduce this (tried Chrome & Safari as well), but I don't have a system as old as 10.6.x on hand.... I'm running 10.9.5.

Looking into the font, I suspect this may be related to the construction of the "Odieresis" and similar glyphs. I see things like

    <TTGlyph name="Odieresis" xMin="58" yMin="-12" xMax="634" yMax="888">
      <component glyphName="O" x="0" y="0" flags="0x0"/>
      <component glyphName="uni0308.case" x="531" y="0" flags="0x0"/>

where "Odieresis" is built from the "O" component (fine), and "uni0308.case" with an x-offset. Looking further, we find that "uni0308.case" is itself a composite glyph:

    <TTGlyph name="uni0308.case" xMin="-342" yMin="782" xMax="-30" yMax="888">
      <component glyphName="uni0308" x="0" y="126" flags="0x0"/>

and the base "uni0308" contains the actual outline of the dieresis (umlaut), designed to appear to the left of the origin:

    <TTGlyph name="uni0308" xMin="-342" yMin="656" xMax="-30" yMax="762">
      <contour>
      ........

My guess is that some versions of the Apple font engine (on 10.6, apparently, but not on 10.9) are mis-handing this situation of multi-level composite glyphs with component offsets.

It looks like this may be a bug in the TrueType rasterizer, but if my guess here is correct, it should be possible to work around it by ensuring that composite glyphs are built using the "original" outline components directly, rather than multiple levels of composition.

**Comment by funtoosh** [comment]
Wow, thx for taking a look into the depths of the font … that should be the problem, I guess.
I had a look around and couldn't reproduce it on Linux, Windows, iOS, Mac OS X 10.10 …

Still pretty weird to see this on both the client's and (some of) my machines.

**Comment by jfkthame** [comment]
Could you check the exact OS version that's used on each of the various machines where it renders incorrectly? You mentioned Mac OS X 10.6.8 earlier; is the failure limited to ONLY this version, or does it happen on any others? Does it fail consistently on EVERY 10.6.8 machine?

**Comment by carrois** [comment]
As it seems be an OSX problem we put the 4.103 and 3.203 build back on our server for download.

**Comment by schriftgestalt** [comment]
The fonts are fine, the spec allows nested components. But if it is not rendering properly, I’ll change it to the old behavior.

**Comment by jfkthame** [comment]
@schriftgestalt  Yes, agreed; AFAICS the fonts look correct, and this appears to be a bug in (certain version(s) of) Apple's truetype engine. But if Glyphs can "dereference" multi-level references so that in all cases, a composite glyph just uses basic outline glyphs as its components, that should avoid the problem.

So when exporting a composite glyph from the design, it would need to look at each component, and if that is itself a composite glyph, replace it with its component(s) and adjust the offsets accordingly; and do this recursively as necessary to "flatten" all composites to single-level.

**Comment by schriftgestalt** [comment]
I now what to do. Glyphs did that until recently but the I changed it to fixed another problem. And it would reduce the file size a bit.

**Comment by funtoosh** [comment]
Mhm, so I downloaded the 4.103 version today, put it in the server, emptied all caches, but -- nothing changed! As the capital umlaut gets used quite a lot on the site, and as the Ü is part of the name of the festival, any help is appreciated ...

As to which versions of Mac OS are affected: so far, I can only confirm 10.6.8, will try to compare some of my colleagues macs in the office next week. I suspect 10.7 or 8 will have the same problem.

http://www.flurstuecke.com/015/danke

![bildschirmfoto 2015-06-06 um 11 43 57](https://cloud.githubusercontent.com/assets/506433/8019182/3dd228f2-0c41-11e5-91cd-cc4151a498cc.png)

Cheers,
-martin

**Comment by patrykdesign** [comment]
@funtoosh just uploaded 4.104, I believe it may have solved this issue. @carrois was targetting to get this fixed.

**Comment by patrykdesign** [comment]
@funtoosh we added v.4.105 a few weeks back with some more fixes, can you confirm its fixed now? Thanks

**Comment by funtoosh** [comment]
Hi Patryk,

sorry for the late reply :~{
The project has ended a couple of weeks ago, but I just uploaded the  
new files to the server and should be able to check if it works over  
the weekend, on an old iMac @ home.

Thanx for your efforts!!

	Cheers,
	-f



Am 10.08.2015 um 23:52 schrieb Patryk Adamczyk:

**Comment by funtoosh** [comment]
Yes! Works! Perfect!

Thanx loads everybody.

![bildschirmfoto 2015-08-24 um 21 50 09](https://cloud.githubusercontent.com/assets/506433/9450755/ceea8864-4aaa-11e5-9db8-777ff5a2deff.png)
